GO_EASY_ON_ME=1
TWEAK_NAME = Infinifolders
OPTFLAG = -O1
Infinifolders_OBJCC_FILES = Infinifolders.xmi infinishared/Infinishared.xmi
Infinifolders_FRAMEWORKS = UIKit CoreGraphics QuartzCore

include framework/makefiles/common.mk
include framework/makefiles/tweak.mk
