GO_EASY_ON_ME=1
TWEAK_NAME = Infinifolders
Infinifolders_OBJCC_FILES = Infinifolders.mm infinishared/Infinishared.mm
Infinifolders_FRAMEWORKS = UIKit CoreGraphics QuartzCore

include framework/makefiles/common.mk
include framework/makefiles/tweak.mk
