GO_EASY_ON_ME=1
TWEAK_NAME = Infinifolders
OPTFLAG = -O1
Infinifolders_OBJCC_FILES = Infinifolders.xmi infinishared/Infinishared.xmi
Infinifolders_FRAMEWORKS = UIKit CoreGraphics QuartzCore

include theos/makefiles/common.mk
include theos/makefiles/tweak.mk
