GO_EASY_ON_ME=1
TWEAK_NAME = Infiniboard
OPTFLAG = -O1
Infiniboard_OBJCC_FILES = Infiniboard.xmi ../infinishared/Infinishared.xmi
Infiniboard_FRAMEWORKS = UIKit CoreGraphics QuartzCore
Infiniboard_LDFLAGS = -llockdown

include framework/makefiles/common.mk
include framework/makefiles/tweak.mk
