GO_EASY_ON_ME=1
TWEAK_NAME = Infiniboard
Infiniboard_OBJCC_FILES = Infiniboard.mm infinishared/Infinishared.mm
Infiniboard_FRAMEWORKS = UIKit CoreGraphics QuartzCore
Infiniboard_LDFLAGS = -llockdown
Infiniboard_CFLAGS = -Wno-missing-declarations

include framework/makefiles/common.mk
include framework/makefiles/tweak.mk
